#pragma once

#include <glm/glm.hpp>

#define TEXTURE_DIMENSION 0.25f
#define BLOCK_RENDER_SIZE 0.50f

enum BlockType
{
    AIR = 0,
    GRASS = 1,
    STONE = 2,
    SNOW = 3,
    SAND = 4,
    WOOD = 5,
    LEAVES = 6,
    WATER = 7,
};

struct BlockUV {
    glm::vec2 Side[4];
    glm::vec2 Top[4];
    glm::vec2 Bottom[4];
};

static const BlockUV BlockUVTable[] = {
	// GRASS
    {
        // Side
        {{TEXTURE_DIMENSION * 1.0f, TEXTURE_DIMENSION * 2.0f},
        {TEXTURE_DIMENSION * 2.0f, TEXTURE_DIMENSION * 2.0f},
        {TEXTURE_DIMENSION * 2.0f, TEXTURE_DIMENSION * 3.0f},
        {TEXTURE_DIMENSION * 1.0f, TEXTURE_DIMENSION * 3.0f}},
        // Top
        {{TEXTURE_DIMENSION * 2.0f, TEXTURE_DIMENSION * 3.0f},
        {TEXTURE_DIMENSION * 3.0f, TEXTURE_DIMENSION * 3.0f},
        {TEXTURE_DIMENSION * 3.0f, TEXTURE_DIMENSION * 2.0f},
        {TEXTURE_DIMENSION * 2.0f, TEXTURE_DIMENSION * 2.0f}},
        // Bottom
        {{TEXTURE_DIMENSION * 0.0f, TEXTURE_DIMENSION * 2.0f},
        {TEXTURE_DIMENSION * 1.0f, TEXTURE_DIMENSION * 2.0f},
        {TEXTURE_DIMENSION * 1.0f, TEXTURE_DIMENSION * 1.0f},
        {TEXTURE_DIMENSION * 0.0f, TEXTURE_DIMENSION * 1.0f}},
    },
    // STONE
    {   
        // Side
        {{TEXTURE_DIMENSION * 0.0f, TEXTURE_DIMENSION * 3.0f},
        {TEXTURE_DIMENSION * 1.0f, TEXTURE_DIMENSION * 3.0f},
        {TEXTURE_DIMENSION * 1.0f, TEXTURE_DIMENSION * 2.0f},
        {TEXTURE_DIMENSION * 0.0f, TEXTURE_DIMENSION * 2.0f}},
        // Top
        {{TEXTURE_DIMENSION * 0.0f, TEXTURE_DIMENSION * 3.0f},
        {TEXTURE_DIMENSION * 1.0f, TEXTURE_DIMENSION * 3.0f},
        {TEXTURE_DIMENSION * 1.0f, TEXTURE_DIMENSION * 2.0f},
        {TEXTURE_DIMENSION * 0.0f, TEXTURE_DIMENSION * 2.0f}},
        // Bottom
        {{TEXTURE_DIMENSION * 0.0f, TEXTURE_DIMENSION * 3.0f},
        {TEXTURE_DIMENSION * 1.0f, TEXTURE_DIMENSION * 3.0f},
        {TEXTURE_DIMENSION * 1.0f, TEXTURE_DIMENSION * 2.0f},
        {TEXTURE_DIMENSION * 0.0f, TEXTURE_DIMENSION * 2.0f}},
    },
    // SNOW
    {  
        // Side
		{{TEXTURE_DIMENSION * 1.0f, TEXTURE_DIMENSION * 1.0f},
		{TEXTURE_DIMENSION * 2.0f, TEXTURE_DIMENSION * 1.0f},
		{TEXTURE_DIMENSION * 2.0f, TEXTURE_DIMENSION * 2.0f},
		{TEXTURE_DIMENSION * 1.0f, TEXTURE_DIMENSION * 2.0f}},
        // Top
		{{TEXTURE_DIMENSION * 2.0f, TEXTURE_DIMENSION * 2.0f},
		{TEXTURE_DIMENSION * 3.0f, TEXTURE_DIMENSION * 2.0f},
		{TEXTURE_DIMENSION * 3.0f, TEXTURE_DIMENSION * 1.0f},
		{TEXTURE_DIMENSION * 2.0f, TEXTURE_DIMENSION * 1.0f}},
        // Bottom
		{{TEXTURE_DIMENSION * 0.0f, TEXTURE_DIMENSION * 2.0f},
		{TEXTURE_DIMENSION * 1.0f, TEXTURE_DIMENSION * 2.0f},
		{TEXTURE_DIMENSION * 1.0f, TEXTURE_DIMENSION * 1.0f},
		{TEXTURE_DIMENSION * 0.0f, TEXTURE_DIMENSION * 1.0f}},
    },
    // SAND
    {
        // Side
        {{TEXTURE_DIMENSION * 0.0f, TEXTURE_DIMENSION * 1.0f},
        {TEXTURE_DIMENSION * 1.0f, TEXTURE_DIMENSION * 1.0f},
        {TEXTURE_DIMENSION * 1.0f, TEXTURE_DIMENSION * 0.0f},
        {TEXTURE_DIMENSION * 0.0f, TEXTURE_DIMENSION * 0.0f}},
        // Top
		{{TEXTURE_DIMENSION * 0.0f, TEXTURE_DIMENSION * 1.0f},
        {TEXTURE_DIMENSION * 1.0f, TEXTURE_DIMENSION * 1.0f},
        {TEXTURE_DIMENSION * 1.0f, TEXTURE_DIMENSION * 0.0f},
        {TEXTURE_DIMENSION * 0.0f, TEXTURE_DIMENSION * 0.0f}},
        // Bottom
		{{TEXTURE_DIMENSION * 0.0f, TEXTURE_DIMENSION * 1.0f},
        {TEXTURE_DIMENSION * 1.0f, TEXTURE_DIMENSION * 1.0f},
        {TEXTURE_DIMENSION * 1.0f, TEXTURE_DIMENSION * 0.0f},
        {TEXTURE_DIMENSION * 0.0f, TEXTURE_DIMENSION * 0.0f}},
    },
    // WOOD
    {
        // Side
	    {{TEXTURE_DIMENSION * 1.0f, TEXTURE_DIMENSION * 1.0f},
	    {TEXTURE_DIMENSION * 2.0f, TEXTURE_DIMENSION * 1.0f},
	    {TEXTURE_DIMENSION * 2.0f, TEXTURE_DIMENSION * 0.0f},
	    {TEXTURE_DIMENSION * 1.0f, TEXTURE_DIMENSION * 0.0f}},
        // Top
		{{TEXTURE_DIMENSION * 3.0f, TEXTURE_DIMENSION * 1.0f},
		{TEXTURE_DIMENSION * 4.0f, TEXTURE_DIMENSION * 1.0f},
		{TEXTURE_DIMENSION * 4.0f, TEXTURE_DIMENSION * 2.0f},
		{TEXTURE_DIMENSION * 3.0f, TEXTURE_DIMENSION * 2.0f}},
        // Bottom
		{{TEXTURE_DIMENSION * 3.0f, TEXTURE_DIMENSION * 1.0f},
		{TEXTURE_DIMENSION * 4.0f, TEXTURE_DIMENSION * 1.0f},
		{TEXTURE_DIMENSION * 4.0f, TEXTURE_DIMENSION * 2.0f},
		{TEXTURE_DIMENSION * 3.0f, TEXTURE_DIMENSION * 2.0f}},
    },
    // LEAVES
    {   
        // Side
	    {{TEXTURE_DIMENSION * 2.0f, TEXTURE_DIMENSION * 1.0f},
	    {TEXTURE_DIMENSION * 3.0f, TEXTURE_DIMENSION * 1.0f},
	    {TEXTURE_DIMENSION * 3.0f, TEXTURE_DIMENSION * 0.0f},
	    {TEXTURE_DIMENSION * 2.0f, TEXTURE_DIMENSION * 0.0f}},
        // Top
		{{TEXTURE_DIMENSION * 2.0f, TEXTURE_DIMENSION * 0.0f},
		{TEXTURE_DIMENSION * 3.0f, TEXTURE_DIMENSION * 0.0f},
		{TEXTURE_DIMENSION * 3.0f, TEXTURE_DIMENSION * 1.0f},
		{TEXTURE_DIMENSION * 2.0f, TEXTURE_DIMENSION * 1.0f}},
        // Bottom
		{{TEXTURE_DIMENSION * 2.0f, TEXTURE_DIMENSION * 0.0f},
		{TEXTURE_DIMENSION * 3.0f, TEXTURE_DIMENSION * 0.0f},
		{TEXTURE_DIMENSION * 3.0f, TEXTURE_DIMENSION * 1.0f},
		{TEXTURE_DIMENSION * 2.0f, TEXTURE_DIMENSION * 1.0f}},
    },
    // WATER
    {   
        // Side
		{{TEXTURE_DIMENSION * 3.0f, TEXTURE_DIMENSION * 1.0f},
		{TEXTURE_DIMENSION * 4.0f, TEXTURE_DIMENSION * 1.0f},
		{TEXTURE_DIMENSION * 4.0f, TEXTURE_DIMENSION * 0.0f},
		{TEXTURE_DIMENSION * 3.0f, TEXTURE_DIMENSION * 0.0f}},
        // Top
		{{TEXTURE_DIMENSION * 3.0f, TEXTURE_DIMENSION * 0.0f},
		{TEXTURE_DIMENSION * 4.0f, TEXTURE_DIMENSION * 0.0f},
		{TEXTURE_DIMENSION * 4.0f, TEXTURE_DIMENSION * 1.0f},
		{TEXTURE_DIMENSION * 3.0f, TEXTURE_DIMENSION * 1.0f}},
        // Bottom
		{{TEXTURE_DIMENSION * 3.0f, TEXTURE_DIMENSION * 0.0f},
		{TEXTURE_DIMENSION * 4.0f, TEXTURE_DIMENSION * 0.0f},
		{TEXTURE_DIMENSION * 4.0f, TEXTURE_DIMENSION * 1.0f},
		{TEXTURE_DIMENSION * 3.0f, TEXTURE_DIMENSION * 1.0f}},
    }
};